# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AmigoDash' do

pod 'AFNetworking', '2.5.4'
pod 'Stripe'
pod 'PaymentKit'
pod 'SDWebImage', '~>3.7'

end

